# Generated by Django 5.0.1 on 2024-07-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_commercial_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial_project',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commercial_project',
            name='total_tower',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='commercial_project',
            name='totle_unit',
            field=models.CharField(max_length=5),
        ),
    ]
